name: Jest
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dependencies
        run: echo '${{ secrets.FIREBASE_CONFIG }}' > .firebase_config.ts
      - name: Install modules
        run: npm i
      - name: Run tests
        run: npm test
